#!/bin/bash

echo "=========================================="
echo "Generate JWT Token"
echo "=========================================="
echo ""
echo "Use the API login endpoint to get JWT tokens:"
echo ""
echo "1. Register a user first:"
echo "   curl -X POST http://localhost:3000/api/auth/register \\"
echo "     -H \"Content-Type: application/json\" \\"
echo "     -d '{\"email\":\"user@example.com\",\"password\":\"pass123\",\"role\":\"MANUFACTURER\"}'"
echo ""
echo "2. Login to get token:"
echo "   curl -X POST http://localhost:3000/api/auth/login \\"
echo "     -H \"Content-Type: application/json\" \\"
echo "     -d '{\"email\":\"user@example.com\",\"password\":\"pass123\"}'"
echo ""
echo "The response will include a JWT token in the 'token' field."
echo ""
