// Anchor IDL for solana_test_project
// This file imports the JSON IDL generated by Anchor
import idlJson from "./solana_test_project.json";

// Export the IDL for use with Anchor
export const IDL = idlJson as any;
export type SolanaTestProjectIDL = typeof idlJson;
