#!/bin/bash

echo "=========================================="
echo "Create Test Users"
echo "=========================================="
echo ""
echo "Use the API register endpoint to create users:"
echo ""
echo "1. Create MANUFACTURER user:"
echo "   curl -X POST http://localhost:3000/api/auth/register \\"
echo "     -H \"Content-Type: application/json\" \\"
echo "     -d '{\"email\":\"manufacturer@test.com\",\"password\":\"test123\",\"name\":\"Test Manufacturer\",\"role\":\"MANUFACTURER\"}'"
echo ""
echo "2. Create ADMIN user:"
echo "   curl -X POST http://localhost:3000/api/auth/register \\"
echo "     -H \"Content-Type: application/json\" \\"
echo "     -d '{\"email\":\"admin@test.com\",\"password\":\"test123\",\"name\":\"Test Admin\",\"role\":\"ADMIN\"}'"
echo ""
echo "Both users will be created with password: test123"
echo ""
